# Generated by Django 4.1.3 on 2022-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('password', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
